//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "proyectoX",
                apiDescription: "Pet Store",
                paths: [
                 "/pets", "/pets/123",                ],
                endPoint: "https://bw7mtqti03.execute-api.us-east-1.amazonaws.com/prueba/",
                apiClient: AWSAPI_EURYB3PQK8_ProyectoXMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
