//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_gxex6z0GA"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "33koi4ht12ctsdfrpigfvgim1e"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "12qo373r0mhop90rg8d1hcvvgdupbmro2lca5n87sns6npclamnm"

// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .USEast1
